### ISSUE TITLE
Support "--from-clipboard" option for copy command

### ISSUE THREAD

**Issue by nakabonne** [nakabonne/pbgopy#17]
It would be nice if we can send the data stored at the clipboard to pbgopy server.

```
Flags:
  -c  --from-clipboard Put the data at the local clipboard into pbgopy server
```

Example:
```
pbgopy copy -c
```

It may be helpful: https://github.com/atotto/clipboard

**Comment by thealamu** [comment]
Seems like a ```goodfirstissue``` too

**Comment by nakabonne** [comment]
Yup, it's definitely a good first issue.
