### ISSUE TITLE
Support option to specify buffer size

### ISSUE THREAD

**Issue by nakabonne** [nakabonne/pbgopy#2]
Currently, it uses `ReadAll()` to read from stdin, but that's dangerous and it may cause OOM.

Instead, we'd better directly stream it via HTTP. That way doesn't require to buffer at all.
https://github.com/nakabonne/pbgopy/blob/9e86a266f03feaa369b22e6933687c1a1e704e1e/commands/copy.go#L49

**Comment by thealamu** [comment]
I would like to work on this but you talk about OOM. Wouldn't that still happen if you keep storing the streamed data in the cache? Or do you mean streaming directly to the "pasting device"? What would a perfect implementation be?

**Comment by nakabonne** [comment]
@thealamu Sorry for the confusion. It doesn't mean streaming directly to the "pasting device". It means to stream it to the pbgopy server. However, pbgopy supports end-to-end encryption, so I'm beginning to feel it's not appropriate.

`iouti.ReadAll()` continues to buffer the input from the STDIN until EOF appears. If there is incorrect input, it could eat up the memory on the "copying device". I'm trying to think of something else to do 🤔

**Comment by thealamu** [comment]
I don't know, but maybe capping the number of bytes over the buffered read and dedicating a streaming endpoint for much larger data. With the streaming endpoint, another device must be pasting to avoid OOM on the "copying device". What do you think? Although, I am not sure how encryption fits in here yet.

**Comment by nakabonne** [comment]
Let's change it to fail if you try to copy more data than the specified size with the `--size(MB)` option. By default 500MB is given.

**Comment by thealamu** [comment]
Okay, but that sounds like a 'quick fix' rather than a lasting solution?

**Comment by thealamu** [comment]
Okay, please assign to me.

**Comment by nakabonne** [comment]
@thealamu Yes, I'll be happy with that. Your help is essential.

**Comment by thealamu** [comment]
Can this be closed now?

**Comment by nakabonne** [comment]
Yes, resolved by https://github.com/nakabonne/pbgopy/pull/10
